Purpose to add Animation extensions
felixblaschke/supercharged pull request #11
Opened 2020-07-27 14:44 UTC by jascodes

Hey @felixblaschke 
Awesome projects!!!🍻

Please check out couple of Animation extensions, that I am personally using. Let me know if you think if it make sense to add them here. Also feel free to make edits if you wish.

Stay Safe
Jas

2020-07-27 15:45 UTC, felixblaschke commented
Hi Jas! Thank you for contributing to this project. I cloned it and tried to figure out how to use it.

**Is this the desired use case you are addressing with that functions?**

```dart
AnimationController controller = /* ... */;
Animation<double> width = 100.0.tweenTo(200.0)
        .animate(controller.interval(0.5, 1.0, curve: Curves.elasticInOut));
```

I found out that it applies are curvy behavior to the animation and also snaps the animation to the interval. The other function you committed does only the first part, right?

2020-07-27 17:41 UTC, jascodes commented
Hey thanks for getting back.

So .interval is just for interval, passing curves is optional. I myself like chaining it.
`controller.interval(0.5,1.0).curve(elasticInOut)

Offcourse single use can be also usefull.

`controller.interval(0.5,1.0)` or
`controller.curve(Curves.elasticInOut)`

The way I use to stagger same or multiple widget with applying diff. interval to same controller.

```
WidgetA(controller: controller.interval(0,0.3))
WidgetB(controller: controller.interval(0.3,0.7))
WidgetA(controller: controller.interval(0.7,1))
```

BTW how do you compose your animations, similarly or some what diff. Would love to hear. 
Thx

2020-07-27 17:59 UTC, felixblaschke commented
I never worked that way... passing Animation objects into widget constructors. But how do they redraw? Are these all stateful widgets?

How I do animation? I wrote (the maybe most popular 😆 ) Flutter animation framework to solve such issues.

For staggering I have my **MultiTween**:

```dart
import 'package:flutter/material.dart';
import 'package:simple_animations/simple_animations.dart';
import 'package:supercharged/supercharged.dart';

void main() => runApp(MyApp());

// Create enum that defines the animated properties
enum AniProps { width, height, color }

class MyApp extends StatelessWidget {

  // Specify your tween
  final _tween = MultiTween<AniProps>()
    ..add(AniProps.width, 0.0.tweenTo(100.0), 1000.milliseconds)
    ..add(AniProps.width, 100.0.tweenTo(200.0), 500.milliseconds)
    ..add(AniProps.height, 0.0.tweenTo(200.0), 2500.milliseconds)
    ..add(AniProps.color, Colors.red.tweenTo(Colors.blue), 3.seconds);

  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      home: Scaffold(
        backgroundColor: Colors.white,
        body: Center(
          child: PlayAnimation<MultiTweenValues<AniProps>>(
            tween: _tween, // Pass in tween
            duration: _tween.duration, // Obtain duration from MultiTween
            builder: (context, child, value) {
              return Container(
                width: value.get(AniProps.width), // Get animated value for width
                height: value.get(AniProps.height), // Get animated value for height
                color: value.get(AniProps.color), // Get animated value for color
              );
            },
          ),
        ),
      ),
    );
  }
}
```
Creates that: ![](https://raw.githubusercontent.com/felixblaschke/simple_animations_documentation_assets/master/sa_multi_tween/v1/multitween-example-1.gif)

Take a look I've you haven't already: https://pub.dev/packages/simple_animations

2020-07-27 18:20 UTC, jascodes commented
😁👍 Indeed most famous. I use all three parts of simple_animation and I much appreciate them all. I use simple_package in let's say single widget component. I might have multiple of these component, generally I want some stagger when they appear on page. I do it by adjusting intervals. Maybe there is better way to do this... 😂

Anyhow its I will maybe share some code sometime; for you to see and comment. It can go into examples of simple_animations, if something interesting turns out.

I also have suggestion to improve Multitween, I will open issue to discuss it sometime and submit PR or something.

Cheers

2020-07-28 10:33 UTC, felixblaschke commented
I slept a night on your propose.

> ```
> WidgetA(controller: controller.interval(0,0.3))
> WidgetB(controller: controller.interval(0.3,0.7))
> WidgetA(controller: controller.interval(0.7,1))
> ```

I don't think it's a good general style to use in flutter. It forces stateless widgets to be stateful widgets in order to evaluate the Animation. I think it will increase the overall complexity of the application. A third person that read this code might have problem to understand it. In other words: I believe this will lead to code hiding instead of encapsulation.

I'll propose to do something like

```dart
WidgetA(width: widthAnimation.value),
WidgetB(width: widthAnimation.value),
// ...
```
Working with real values instead of a slice of an animation. These widget act immutable due to it's stateless nature.

But I also didn't tried it myself. So I maybe wrong on this. If you also believe so, you can publish an example repo where I can see/feel the value of this strategy and get some insights.

2020-07-28 14:42 UTC, jascodes commented
Oh I do follow your pattern but only in case its okay for entire widget to be rebuilt.
```
WidgetA(width: widthAnimation.value),
WidgetB(width: widthAnimation.value),
```
Animatedbuilder has optimisation where if allow you to skip rebuild of subtree of child. But it's not only controller(s) I pass to animation object, I also said; I pass flags also. These flags will determine the variation in animation with tween's being conditionally used and evaluated.  
```
WidgetA(controller: controller.interval(0,0.3),appearStyle:EnumAppear.flat)
WidgetB(controller: controller.interval(0.3,0.7),bounce:true,)
WidgetA(controller: controller.interval(0.7,1),skipX:true)
```
I don't know if my pattern, which grew organically for me based on real world challenges is most optimal. I guess thats why I am having this talk 😁.

2020-07-29 05:30 UTC, felixblaschke commented
Sure... `AnimatedBuilder`!!! Now you changed my mind 😄 . If we now change the widget's parameter name from `controller` to something that describes the actual animation, like

`ProfilePictureWidget(iconFadeInAnimation: controller.interval(0.0, 0.3)` ... is makes all sense. If we use the `AnimatedBuilder` inside that have a good encapsulation without having boilerplate code. Now I understood the full potential of this and must revert myself.

I also see some convenience potential for something like `controller.split(from: 1.seconds, to: 2.seconds, baseDuration: 5.seconds)` that computes the interval for you.

Here the code I tried. Stop me if I've done it wrong.

```dart
import 'package:flutter/material.dart';
import 'package:supercharged/supercharged.dart';

void main() => runApp(MyApp());

class MyApp extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return MaterialApp(
        home: Scaffold(
      body: MyWidget(),
    ));
  }
}

class MyWidget extends StatefulWidget {
  @override
  _MyWidgetState createState() => _MyWidgetState();
}

class _MyWidgetState extends State<MyWidget>
    with SingleTickerProviderStateMixin {
  AnimationController controller;

  Animation<double> width;

  @override
  void initState() {
    controller = AnimationController(vsync: this);
    controller.duration = Duration(seconds: 5);
    controller.forward();
    super.initState();
  }

  @override
  Widget build(BuildContext context) {
    return Center(
        child: SomeContainer(controller.interval(0.5, 1.0)));
  }
}

class SomeContainer extends StatelessWidget {
  final Animation<double> animation;

  SomeContainer(this.animation);

  @override
  Widget build(BuildContext context) {
    return AnimatedBuilder(
      animation: animation,
      builder: (context, child) {
        return Container(
          width: 100.0.tweenTo(200.0).curved(Curves.elasticIn).animate(animation).value,
          height: 200.0.tweenTo(400.0).curved(Curves.elasticOut).animate(animation).value,
          color: Colors.blue,
        );
      },
    );
  }
}
```

Let's start getting your changes in. I will start reviewing your changes if you like.

2020-07-29 05:36 UTC, felixblaschke requested changes

2020-07-29 05:36 UTC, felixblaschke commented on lib/animation/animation.dart
> +extension Animation_ on Animation {
We need generics annotation here, since `drive` function is only applikable  on `Animation<double>`

2020-07-29 05:36 UTC, felixblaschke commented on lib/animation/animation.dart
> +  /// Optionally can passe [Curve] as well by pass curve object at last parameter.
Description needs spell checking

2020-07-29 05:36 UTC, felixblaschke commented on lib/animation/animation.dart
> +  /// controller.interval(0.0, 1.0,curve:Curves.elasticOut)
dart formatting (missing whitespace)

2020-07-29 05:36 UTC, felixblaschke commented on lib/animation/animation.dart
> +  Animation interval(double begin, double end, {Curve curve}) {
missing unit test for function

2020-07-29 05:36 UTC, felixblaschke commented on lib/animation/animation.dart
> +  Animation curve(Curve curve) {
missing unit test for function

2020-07-29 05:36 UTC, felixblaschke commented on lib/animation/animation.dart
> +    // Value Guard
I don't think we need that "value guard" comment. `assert`s should be known to developers.

2020-07-29 05:36 UTC, felixblaschke commented on lib/animation/animation.dart
> +  /// Returns an [Animation] after appling [CurveTween]. You can just pass curve
spell checking

2020-07-29 08:32 UTC, jascodes commented
I actually myself don't use c

2020-07-29 08:45 UTC, jascodes commented
I don't use parameter name `controller`😂, I was just saying it here. Thanks for reviewing code. I agree with every point, It was haslty cobled up as I first wanted to know if you agreed with me. I also comment on other things you said in your earlier reply, but for couple of days I will be super busy. I want to resume our conversation and more formalize this PR soon. Let me know if your okay to say hello to you over video/audio sometime. I want to pick your brain over another PR purposal, I am planing for MultiTween; if you wish to stick this pattern, I am also fine with that.
Be back in couple of day....

2020-07-29 09:16 UTC, felixblaschke commented
No problem. Take your time 😄 . Just response / update this if you have time.

2020-08-01 09:26 UTC, jascodes commented
Feel free to do any edits or refactoring.

2020-08-02 06:23 UTC, felixblaschke approved these changes
Looks fine.

2020-08-02 06:23 UTC, merged

2020-08-04 20:16 UTC, felixblaschke commented
Changes went live with version 1.8.3